# Default values for python.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: Always
  repository: eyjohn/websockettest
  tag: latest
service:
  name: websockettest
  type: NodePort
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: true
  hosts:
    - websockettest.evkube.evdev.me
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
  - hosts:
    - websockettest.evkube.evdev.me
    secretName: websockettest-tls
